[build]
  command = "CI= npm install && npm run build"
  publish = "build"

[functions]
  directory = "netlify/functions"

# Add this new section at the bottom
[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
