[build]
  command = "npm install && npx react-scripts build"
  publish = "build"

[functions]
  directory = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
