# This tells Netlify how to build your site
[build]
  command = "npm install && npm run build"
  publish = "build"

# This tells Netlify where your serverless functions are
[functions]
  directory = "netlify/functions"

# This rule is for single-page applications like React
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
